import { SprintAgentsConfig } from './config.js';
import { exec, execLive, log } from './utils.js';

export function createPR(sourceBranch: string, title: string, config: SprintAgentsConfig): void {
	// Push branch to remote
	log(`Pushing '${sourceBranch}' to ${config.remote}...`);
	execLive(`git push -u ${config.remote} ${sourceBranch}`);

	if (config.platform === 'github') {
		createGitHubPR(sourceBranch, title, config);
	} else {
		createGitLabMR(sourceBranch, title, config);
	}
}

function createGitHubPR(sourceBranch: string, title: string, config: SprintAgentsConfig): void {
	// Check if PR already exists
	try {
		const existing = exec(
			`gh pr list --head ${sourceBranch} --base ${config.baseBranch} --state open --json url --jq '.[0].url'`,
		);
		if (existing) {
			log(`Pull request already exists (updated with push): ${existing}`);
			return;
		}
	} catch {
		// No existing PR, create one
	}

	try {
		execLive(
			`gh pr create --base ${config.baseBranch} --head ${sourceBranch} --title "${title.replace(/"/g, '\\"')}"  --body "Automatically generated by sprint-agents."`,
		);
	} catch (e) {
		console.error('WARNING: Failed to create pull request.');
		console.error('Branch was pushed — create PR manually.');
	}
}

function createGitLabMR(sourceBranch: string, title: string, config: SprintAgentsConfig): void {
	const token = process.env.GITLAB_TOKEN;
	if (!token) {
		console.error('ERROR: GITLAB_TOKEN not set');
		console.error('Branch was pushed — create MR manually.');
		return;
	}

	const projectId = config.repo.replace(/\//g, '%2F');
	const apiBase = 'https://gitlab.com/api/v4';

	// Use python3 for reliable GitLab API calls (same approach as MOP)
	const script = `
import urllib.request, json, sys

token = '${token}'
api = '${apiBase}'
project = '${projectId}'
source = '''${sourceBranch}'''
target = '${config.baseBranch}'
title = '''${title.replace(/'/g, "\\'")}'''

headers = {'PRIVATE-TOKEN': token, 'Content-Type': 'application/json'}

# Check existing MRs
req = urllib.request.Request(
    f'{api}/projects/{project}/merge_requests?source_branch={source}&state=opened',
    headers=headers
)
try:
    with urllib.request.urlopen(req) as resp:
        mrs = json.loads(resp.read())
    if mrs:
        print(f'>>> Merge request already exists (updated with push): {mrs[0]["web_url"]}')
        sys.exit(0)
except Exception as e:
    print(f'WARNING: Failed to check existing MRs: {e}')

# Create new MR
data = json.dumps({
    'source_branch': source,
    'target_branch': target,
    'title': title,
    'remove_source_branch': True
}).encode()

req = urllib.request.Request(
    f'{api}/projects/{project}/merge_requests',
    data=data,
    headers=headers,
    method='POST'
)
try:
    with urllib.request.urlopen(req) as resp:
        mr = json.loads(resp.read())
    print(f'>>> Merge request created: {mr["web_url"]}')
except Exception as e:
    print(f'WARNING: Failed to create merge request: {e}')
    print('Branch was pushed — create MR manually.')
`;

	try {
		execLive(`python3 -c ${JSON.stringify(script)}`);
	} catch {
		console.error('WARNING: Failed to create merge request via GitLab API.');
		console.error('Branch was pushed — create MR manually.');
	}
}
